# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget argparse::argparse)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target argparse::argparse
add_library(argparse::argparse INTERFACE IMPORTED)

set_target_properties(argparse::argparse PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
<<<<<<< HEAD
  INTERFACE_INCLUDE_DIRECTORIES "/root/undergrad-thesis-program/libs/argparse/include"
=======
<<<<<<< HEAD
  INTERFACE_INCLUDE_DIRECTORIES "/root/undergrad-thesis-program/libs/argparse/include"
=======
<<<<<<< HEAD
  INTERFACE_INCLUDE_DIRECTORIES "/root/undergrad-thesis-program/libs/argparse/include"
=======
<<<<<<< HEAD
  INTERFACE_INCLUDE_DIRECTORIES "/root/undergrad-thesis-program/libs/argparse/include"
=======
<<<<<<< HEAD
  INTERFACE_INCLUDE_DIRECTORIES "/root/undergrad-thesis-program/libs/argparse/include"
=======
<<<<<<< HEAD
  INTERFACE_INCLUDE_DIRECTORIES "/root/undergrad-thesis-program/libs/argparse/include"
=======
<<<<<<< HEAD
  INTERFACE_INCLUDE_DIRECTORIES "/root/undergrad-thesis-program/libs/argparse/include"
=======
<<<<<<< HEAD
  INTERFACE_INCLUDE_DIRECTORIES "/root/undergrad-thesis-program/libs/argparse/include"
=======
<<<<<<< HEAD
  INTERFACE_INCLUDE_DIRECTORIES "/root/undergrad-thesis-program/libs/argparse/include"
=======
<<<<<<< HEAD
  INTERFACE_INCLUDE_DIRECTORIES "/home/namchee/undergrad-thesis-program/libs/argparse/include"
=======
  INTERFACE_INCLUDE_DIRECTORIES "/root/undergrad-thesis-program/libs/argparse/include"
>>>>>>> e20a75f9fa4d82f7a8feae93539b534b53646bd9
>>>>>>> fe17369e42e9f0e44ecc236fcc8eb3c7c8f5a91d
>>>>>>> db155008e32ac04d88763dedb0c6ad830b46c68c
>>>>>>> b3fdbae4f5b94772e142a4c0bf99d8c079baa0aa
>>>>>>> fa9226b0df8619137c75b9f0adf5d2d6f6d82bd5
>>>>>>> 4aebb8e2a19c5021df06dff249a69957deb4faf7
>>>>>>> 9edbc9a193add4b87ab42bc05b61e95598577c0f
>>>>>>> 9938ec8f276001ffa50d88f4ee47ef0e4ae36965
>>>>>>> 9c88f745296608ab0cdb8bc224ce6db70a056d7d
>>>>>>> 36fb4b0078ee0fa7b7dd80f83cc992f9b0940c39
)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
